ARG PYTHON_VERSION
FROM python:${PYTHON_VERSION}-alpine

# Install dependencies
RUN apk add --no-cache bash

# Create app directory
WORKDIR /app

# Copy entrypoint script
COPY entrypoint.sh /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh

# Set entrypoint
ENTRYPOINT ["/app/entrypoint.sh"] 